### ISSUE TITLE
.NET 4.5 Compat'

### ISSUE THREAD

**Issue by nevercast** [pdelvo/Pdelvo.Minecraft#2]
Hello pdelvo, 

I absolutely love your work with the Minecraft Protocol, curiously though, where can I get the 4.5 rc framework? and is it available for Windows 7? It's not 2012/Win8 RC is it?

Thanks for your time,
Josh

**Comment by pdelvo** [comment]
.net Framework 4.5 RC is avialable for Windows 7, Windows 8 Release Preview, Windows Server 2008, Windows Server 2008 R2 and Windows Server 2012 Release Candidate. You can download it here: http://www.microsoft.com/en-us/download/details.aspx?id=29909. At the download section you find a compiled Version of the stable Minecraft 1.3.1 release of this library. if you want to use the current pre release you have to compile the latest state of the specific branch.

https://github.com/pdelvo/Pdelvo.Minecraft/downloads
