### ISSUE TITLE
BigEndianStream is buggy

### ISSUE THREAD

**Issue by hellow554** [pdelvo/Pdelvo.Minecraft#3]
Hi pdelvo,

your implementation of bigendianstream is really buggy.
At first, look at your implementation of ReadInt64...
You do it like this:

```
if (BitConverter.IsLittleEndian)
    return unchecked((ReadByte () << 56) | (ReadByte () << 48) | (ReadByte () << 40) | (ReadByte () << 32)
        | (ReadByte () << 24) | (ReadByte () << 16) | (ReadByte () << 8) | ReadByte ());
else
    return unchecked((ReadByte ()) | (ReadByte () << 8) | (ReadByte () << 16) | (ReadByte () << 24)
        | (ReadByte () << 32) | (ReadByte () << 40) | (ReadByte () << 48) | (ReadByte () << 56));
```

But thats totally wrong. Two major things.
1. Nevermind of big or little endian. The endian-representation of a byte/short/int/long is only memory related, that means if you "create" a ... whatever... it doesn't matter the endianes. It is always 0x0011223344556677 for a long e.g.
How to store them in the memory it's a different question. But your code would do some wrong calculation here if your system is big endian.
2. Your ReadInt64 is completly wrong. Why? -> Because! How is the << operator in c# is defined? Its not a regular shift operator, it's more than a rotate operator. Lets do a simple test.
A int has 32 bit, right? So this should give the following

```
Console.WriteLine (1 << 1); // 2
Console.WriteLine (1 << 33); // 0 
```

But it gives... yes you are right, 2 and 2, because after the 32nd shift, it rotates, so it does 1 << 1 again.
So... why your code is wrong? Because of this:

```
ReadByte () << 56
```

What is the return type of ReadByte? No... not a byte, but an int. Because the left data type defines it's operation, the << operator for an int is used, that means he rotates 1 time, and then leftshift by 24. But that is not what you want. You want a long to leftshift by 56. That means you have to use a long, not an int.
My implementation of this is

```
unchecked
{
    byte[] l = new byte[8];
    if (Read(l, 0, l.Length) != 8)
         throw new EndOfStreamException();

    long p = 0;
    p |= (long)l[0] << 56;
    p |= (long)l[1] << 48;
    p |= (long)l[2] << 40;
    p |= (long)l[3] << 32;
    p |= (long)l[4] << 24;
    p |= (long)l[5] << 16;
    p |= (long)l[6] << 8;
    p |= (long)l[7]; 
    return p;
}
```

I think this could be done better, but it's corrent and understandable for everyone.
I think you should correct your whole BigEndianStream thing... 
I also recommend strongly to write tests. If you had done it, than you noticed this error before.

Regards

Marcel Hellwig

Ps. I hope you will write tests, they are really usefull and it prevents you from doing such errors in the future ;)

**Comment by pdelvo** [comment]
Hi,

Sorry for this late Response. I was a Little bit bussy because of the GamesCom. Thank you for pointing me at this. I will correct These mistakes in a few days. 

Tests:

I have written tests for testing my protocol implementation, but not added them to this Project on github. I also could do some more. this ReadLong mistake did not get detected. I will add them too, sorry for this
